run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive

linter-settings:
  errcheck:
    check-type-assertions: true

  gocritic:
    enable-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

    revive:
      rules:
        - name: exported
